# Generated by Django 3.2.9 on 2021-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211114_1510'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_amount',
        ),
        migrations.RemoveConstraint(
            model_name='measurement',
            name='unique_measurement',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='measurement',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure',
            new_name='measurement_unit',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('measurement', 'amount'), name='unique_ingredient_amount'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_measurement'),
        ),
    ]
