# Generated by Django 3.2.9 on 2021-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20211108_2205'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='amount__gt_0',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', '0')), name='amount__gt_0'),
        ),
    ]
