# Generated by Django 3.2.9 on 2021-11-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211108_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60), verbose_name='Время приготовления, мин.'),
        ),
    ]
