# Generated by Django 3.2.9 on 2021-11-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
    ]
