# Generated by Django 3.2.9 on 2021-11-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time__gte_0:01:00_minute',
        ),
    ]
