# Generated by Django 3.2.9 on 2021-11-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_cooking_time__gte_0:01:00_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DateTimeField(verbose_name='Время приготовления, мин.'),
        ),
    ]
