# Generated by Django 3.2.9 on 2021-11-09 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time__gte', datetime.timedelta(seconds=60))), name='cooking_time__gte_0:01:00_minute'),
        ),
    ]
