# Generated by Django 3.2.9 on 2021-11-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20211109_1942'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time__gte_0:01:00_minute',
        ),
    ]
